development:
  clients:
      default:
        database: millim_short_url
        hosts:
          - localhost:27017
  options:
    use_utc: true
production:
  clients:
      default:
        database: millim_short_url_production
        hosts:
          - localhost:27017
  options:
    use_utc: true
test:
  clients:
      default:
        database: millim_short_url_test
        hosts:
          - localhost:27017
  options:
    use_utc: true
